version: '3.8'

services:
  backend-gestao-arquivos:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database-gestao-arquivos
    environment:
      DATABASE_URL: "postgres://admin:p@$$w0rd@postgres:5453/gestao_arquivos"
    networks:
      - gestao-arquivos

  database-gestao-arquivos:
    image: postgres:latest
    environment:
      POSTGRES_DB: gestao_arquivos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@$$w0rd
    ports:
      - "5453:5453"
    networks:
      - gestao-arquivos

networks:
  gestao-arquivos:
    driver: bridge
